name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Readme.md' # Ignore changes to Readme.md
      - 'k8s'
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository ## checkout_repository name_sense
        uses: actions/checkout@v4 ## syntax-for-checkout
        # This checks out the code to the GitHub runner

      - name: Set up Java
        uses: actions/setup-java@v4 ## syntax-for-setup java
        with:
          java-version: 11
          java-package: jdk
          distribution: 'temurin' # Temurin distribution of OpenJDK

      - name: Build and compile packages
        run: mvn clean compile ## command to build packages
        # This runs the Maven build command to compile the packages

      - name: Test
        run: mvn test ## command to test packages
        # This runs the Maven test command to execute tests

  Docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        # Check out the repository again for the Docker job

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Sets up Docker Buildx, which is necessary for multi-platform builds

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use secret for username
          password: ${{ secrets.DOCKER_TOKEN}} # Use secret for password

      - name: Build Docker and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tomcat:${{github.run_id}}
          # This builds the Docker image and pushes it to Docker Hub

  Update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: commit
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/studentapp-chart/values.yaml

    - name: Set Git Global Config
      run: |
        echo "Setting global git username and email..."
        git config --global user.name "${{ secrets.username }}"
        git config --global user.email "${{ secrets.useremail }}"
      
    - name: Verify Git Config
      run: |
        echo "Verifying global git configuration..."
        git config --global --get user.name
        git config --global --get user.email
    - name: Commit and push changes
      run: |
        git add helm/studentapp-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push
