# name: CI
# on:
#   push:
#     branches:
#       - main
#     paths-ignore:
#       - 'Readme.md'
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository ##checkout_repository name_sense
#         uses: actions/checkout@v4  ##syntax-for-checkout
#       - name: Set up Java
#         uses: actions/setup-java@v4 ##syntax-for-setup java
#         with:
#           java-version: 11
#           java-package: jdk
#           distribution: 'temurin' 
#       - name: Build and compile packages 
#         run:  mvn clean compile ## command to build packages
#       - name: Test
#         run: mvn test ## command to test packages
#  docker:
#     runs-on: ubuntu-latest
#     needs:  build
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v4

#       - name: Setup Docker Buildx
#         uses: actions/setup-buildx-action@v1

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}

#       - name: Build Docker and push images
#         uses: actions/build-push-action@v6
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_HUB USERNAME }}/tomcat:${{ github.run_id }}

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Readme.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository ##checkout_repository name_sense
        uses: actions/checkout@v4 ##syntax-for-checkout

      - name: Set up Java
        uses: actions/setup-java@v4 ##syntax-for-setup java
        with:
          java-version: 11
          java-package: jdk
          distribution: 'temurin'

      - name: Build and compile packages
        run: mvn clean compile ##command to build packages
   
   test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: mvn test ##command to test packages

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ../Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tomcat:${{ github.run_id }}

